### PR TITLE
RFC6455 conformance for AS3WebSocket. 

### PR DESCRIPTION
**Pull request by rejemy**
I combed through the docs and it does indeed seem that the only practical wire changes between protocol 8 and 13 are the renamed Origin header and a few of the closure status codes. I updated those, but then couldn't help myself and also added multiple subprotocol support as described in the doc. I also optimized the frame masking algorithm to improve throughput by about 2.8x.  I also added a "psedo masking" mode that is useful in particular situations in which the client is embedded and not in danger of being hijacked by a rogue javascript snipped. In this mode, the mask key is always 0, enabling the client to skip the costly masking step completely. Obviously only useful in situations where you're not worried about arbitrary data going across the wire.

I've tested the changes against Jetty 8.1.2, which implements RFC6455 on the server side, everything seems good. I haven't tested through all the error conditions or given it thorough real-world testing.

If there's more here than you want to digest at once, let me know, I can probably break out some of it. Also, I'm new to github so my apologies if it would have been easier for you if I had made a new branch for this. I guess in the worst case I can just go use my own fork from here on out. The magic of github!

### CODE REVIEW

**Comment by theturtle32** [comment]
Awesome, thank you!  The patch looks great!

What do you think about renaming pseudoMasking to useNullMask?  That seems more descriptive to me.

As for best practices on pull requests, this is fine.  Ideally each discreet change would be encapsulated in its own commit - the pull request will include all the commits on the branch you're submitting the pull request for since it diverged from the upstream repo.  Creating a separate branch for your pull request rather than using master is usually desirable because any further commits you push to the branch (master in this case) after submitting the pull request will be automatically added to the open pull request.

For this though, it's fine, don't worry about it.  I'll merge it in right now.  Thanks for the help, I really appreciate it!

**Comment by rejemy** [comment]
Yeah great, rename it! And thank you for making this implementation, it's a big help in making AIR projects that work in all kinds of different situations. If I encounter any issues in testing I will forward fixes to you.

**Comment by theturtle32** [comment]
Will do.  Thanks again!

**Comment by theturtle32** [comment]
I renamed pseudoMasking to useNullMask, and posted the new compiled SWC file to the Downloads section of the repo.

**Comment by theturtle32** [comment]
I made a few more changes:

commit cdf18fab884f3f561f5c086004c1f542738926b3
commit f66b7db52310943c57a8315504a7910c8e8b2d70
commit c6253dc7926394c2a31b893e2ccf78768bef7748
commit 8d14d501520691c3418d7400307d0c952c24d675

**Pull request merged**
